# Generated by Django 3.1.3 on 2020-12-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201218_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_subcategory',
            field=models.CharField(default='', max_length=30),
        ),
    ]
